# Use the following for linting: https://rhysd.github.io/actionlint/
name: Build AGO Launcher

on: [push]

jobs:
  # It runs on every commit pushed to GitHub
  build-ago-launcher:
    runs-on: windows-latest
    # Steps
    steps:
      - uses: actions/checkout@v4

      - name: "Install go 1.24.4"
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4' 

      - name: "Build AGO Launcher"
        run: cd src && go build